# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bookshelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bookshelf
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'GoogleSignIn'
    

  target 'bookshelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bookshelfUITests' do
    # Pods for testing
  end

end
